package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Barrage</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--red:#c44040;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:800px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.btn-s{border-color:var(--green);color:var(--green)}.btn-s:hover{background:var(--green);color:var(--bg)}.card{background:var(--bg2);border:1px solid var(--bg3);padding:.6rem;margin-bottom:.4rem;cursor:pointer;transition:.1s}.card:hover{background:var(--bg3)}.card h3{font-size:.8rem;margin-bottom:.15rem}.card-meta{font-size:.65rem;color:var(--cm);display:flex;gap:.7rem}.run-row{display:flex;align-items:center;gap:.5rem;padding:.35rem .5rem;border-bottom:1px solid var(--bg3);font-size:.72rem}.run-stat{display:inline-flex;gap:.3rem;font-size:.65rem}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:500px}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],input[type=number],select{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}.form-row{display:flex;gap:.5rem}.form-row>*{flex:1}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Barrage</span></h1><button class="btn btn-p" onclick="showNew()">+ Test</button></div>
<div class="main"><div id="upgrade-banner" style="display:none;background:#241e18;border:1px solid #8b3d1a;border-left:3px solid #c45d2c;padding:.6rem 1rem;font-size:.78rem;color:#bfb5a3;margin-bottom:.8rem"><strong style="color:#f0e6d3">Free tier</strong> — 10 items max. <a href="https://stockyard.dev/barrage/" target="_blank" style="color:#e8753a">Upgrade to Pro →</a></div><div id="list"></div><div id="detail" style="display:none;margin-top:1rem"></div></div><div id="modal"></div>
<script>
async function api(u,o){return(await fetch(u,o)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function timeAgo(d){if(!d)return'';const s=Math.floor((Date.now()-new Date(d))/1e3);if(s<60)return s+'s ago';if(s<3600)return Math.floor(s/60)+'m ago';return Math.floor(s/3600)+'h ago'}
async function load(){const d=await api('/api/tests');const tests=d.tests||[];
document.getElementById('list').innerHTML=tests.length?tests.map(t=>'<div class="card" onclick="open_(\''+t.id+'\')"><h3>'+esc(t.name)+'</h3><div class="card-meta"><span>'+t.method+' '+esc(t.url)+'</span><span>'+t.concurrency+'c × '+t.requests+'r</span><span>'+t.run_count+' runs</span></div></div>').join(''):'<div class="empty">No load tests yet. Create one to start.</div>'}
async function open_(id){const[t,rd]=await Promise.all([api('/api/tests/'+id),api('/api/tests/'+id+'/runs')]);
const runs=(rd.runs||[]).map(r=>'<div class="run-row"><span style="color:'+(r.status==='done'?'var(--green)':'var(--gold)')+'">'+r.status+'</span><span class="run-stat"><b>'+r.total_requests+'</b>req</span><span class="run-stat" style="color:var(--green)">'+r.successes+'ok</span>'+(r.failures?'<span class="run-stat" style="color:var(--red)">'+r.failures+'fail</span>':'')+
'<span class="run-stat">avg:'+r.avg_ms.toFixed(0)+'ms</span><span class="run-stat">p99:'+r.p99_ms.toFixed(0)+'ms</span><span class="run-stat" style="color:var(--gold)">'+r.req_per_sec.toFixed(1)+'rps</span><span style="color:var(--cm);font-size:.6rem">'+r.duration_ms+'ms</span></div>').join('');
document.getElementById('detail').style.display='block';
document.getElementById('detail').innerHTML='<div style="display:flex;justify-content:space-between;margin-bottom:.5rem"><span style="font-size:.75rem;color:var(--leather)">'+esc(t.name)+' — '+t.method+' '+esc(t.url)+'</span><div style="display:flex;gap:.3rem"><button class="btn btn-s" onclick="run_(\''+id+'\')">▶ Run</button><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="if(confirm(\'Delete?\'))del(\''+id+'\')">Del</button></div></div>'+(runs||'<div class="empty" style="padding:1rem">No runs yet.</div>')}
async function run_(id){await api('/api/tests/'+id+'/run',{method:'POST'});setTimeout(()=>open_(id),2000);load()}
async function del(id){await api('/api/tests/'+id,{method:'DELETE'});document.getElementById('detail').style.display='none';load()}
function showNew(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>New Load Test</h2><label class="fl">Name</label><input type="text" id="nt-name" placeholder="Homepage load test"><label class="fl">URL</label><input type="text" id="nt-url" placeholder="https://example.com/api/health"><div class="form-row"><div><label class="fl">Method</label><select id="nt-method"><option>GET</option><option>POST</option><option>PUT</option></select></div><div><label class="fl">Concurrency</label><input type="number" id="nt-conc" value="10"></div><div><label class="fl">Total Requests</label><input type="number" id="nt-reqs" value="100"></div></div><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="save()">Create</button><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="closeModal()">Cancel</button></div></div></div>'}
async function save(){const b={name:document.getElementById('nt-name').value,url:document.getElementById('nt-url').value,method:document.getElementById('nt-method').value,concurrency:parseInt(document.getElementById('nt-conc').value)||10,requests:parseInt(document.getElementById('nt-reqs').value)||100};if(!b.name||!b.url){alert('Name and URL required');return};await api('/api/tests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();load()}
function closeModal(){document.getElementById('modal').innerHTML=''}
load()
fetch('/api/tier').then(r=>r.json()).then(j=>{if(j.tier==='free'){var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'}}).catch(()=>{var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'});
</script></body></html>`
