package server

var dashboardHTML = []byte(`<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Stockyard Barrage</title><style>:root{--bg:#1a1410;--surface:#241c15;--border:#3d2e1e;--rust:#c4622d;--leather:#8b5e3c;--cream:#f5e6c8;--muted:#7a6550;--text:#e8d5b0}*{box-sizing:border-box;margin:0;padding:0}body{background:var(--bg);color:var(--text);font-family:'JetBrains Mono',monospace,sans-serif;min-height:100vh}header{background:var(--surface);border-bottom:1px solid var(--border);padding:1rem 2rem;display:flex;align-items:center;gap:1rem}.logo{color:var(--rust);font-size:1.25rem;font-weight:700}.badge{background:var(--rust);color:var(--cream);font-size:0.65rem;padding:0.2rem 0.5rem;border-radius:3px;font-weight:600;text-transform:uppercase}main{max-width:1100px;margin:0 auto;padding:2rem}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-bottom:2rem}.stat{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:1.25rem;text-align:center}.stat-value{font-size:1.75rem;font-weight:700;color:var(--rust)}.stat-label{font-size:0.75rem;color:var(--muted);margin-top:0.25rem;text-transform:uppercase;letter-spacing:0.05em}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.card{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:1.5rem}.card h2{font-size:0.85rem;color:var(--muted);text-transform:uppercase;letter-spacing:0.08em;margin-bottom:1rem}.form-row{display:flex;gap:0.5rem;margin-bottom:0.75rem;flex-wrap:wrap;align-items:flex-start}select,input,textarea{background:var(--bg);border:1px solid var(--border);color:var(--text);padding:0.5rem 0.75rem;border-radius:4px;font-family:inherit;font-size:0.85rem}.form-row select,.form-row input{flex:1}textarea{width:100%;min-height:80px;resize:vertical}.btn{background:var(--rust);color:var(--cream);border:none;padding:0.5rem 1rem;border-radius:4px;cursor:pointer;font-family:inherit;font-size:0.85rem;font-weight:600}.btn:hover{opacity:0.85}.btn-sm{padding:0.25rem 0.6rem;font-size:0.75rem}.btn-danger{background:#7a2020}table{width:100%;border-collapse:collapse;font-size:0.82rem}th{text-align:left;color:var(--muted);padding:0.5rem;border-bottom:1px solid var(--border);font-size:0.75rem;text-transform:uppercase}td{padding:0.5rem;border-bottom:1px solid var(--border)}.empty{color:var(--muted);font-size:0.85rem;padding:1rem 0;text-align:center}.full{grid-column:1/-1}.bg{background:var(--bg);border:1px solid var(--border);border-radius:4px;padding:0.75rem;font-size:0.8rem;font-family:monospace;word-break:break-all}.badge-g{background:#1a3a1a;color:#5cb85c;border:1px solid #2d5a2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}.badge-r{background:#3a1a1a;color:#d9534f;border:1px solid #5a2d2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}.badge-y{background:#3a2f1a;color:#f0ad4e;border:1px solid #5a4a2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}</style></head>
<body><header><span class="logo">&#x2B21; Stockyard</span><span style="color:var(--muted)">/</span><span style="color:var(--cream);font-weight:600">Barrage</span><span class="badge">Load Tester</span></header>
<main><div class="stats"><div class="stat"><div class="stat-value" id="s1">0</div><div class="stat-label">Scenarios</div></div><div class="stat"><div class="stat-value" id="s2">0</div><div class="stat-label">Runs</div></div><div class="stat"><div class="stat-value" id="s3">FREE</div><div class="stat-label">Tier</div></div></div><div class="grid">
<div class="card"><h2>New Scenario</h2>
<div class="form-row"><input id="f-name" placeholder="Scenario name"></div>
<div class="form-row"><input id="f-url" placeholder="https://example.com/api"><select id="f-method"><option>GET</option><option>POST</option><option>PUT</option><option>DELETE</option></select></div>
<div class="form-row"><input id="f-conc" type="number" value="10" placeholder="Concurrency"><input id="f-dur" type="number" value="30" placeholder="Duration (s)"></div>
<button class="btn" onclick="createScenario()">Save Scenario</button></div>
<div class="card"><h2>Scenarios</h2><div id="sc-list"><div class="empty">No scenarios</div></div></div>
<div class="card full"><h2>Run History</h2>
<table><thead><tr><th>Scenario</th><th>Requests</th><th>RPS</th><th>Avg Lat</th><th>P99</th><th>Errors</th><th>Status</th></tr></thead>
<tbody id="runs-body"><tr><td colspan="7" class="empty">No runs yet</td></tr></tbody></table></div>
</div></main>
<script>
async function api(m,p,bd){var o={method:m,headers:{"Content-Type":"application/json"}};if(bd)o.body=JSON.stringify(bd);var r=await fetch(p,o);try{return await r.json();}catch(e){return {};}}  
async function load(){var s=await api("GET","/api/stats");var l=await api("GET","/api/limits");document.getElementById("s1").textContent=s.scenarios||0;document.getElementById("s2").textContent=s.runs||0;document.getElementById("s3").textContent=(l.tier||"free").toUpperCase();loadScenarios();loadRuns();}
async function loadScenarios(){var data=await api("GET","/api/scenarios");var el=document.getElementById("sc-list");if(!data||!data.length){el.innerHTML="<div class='empty'>No scenarios</div>";return;}el.innerHTML=data.map(function(s){return "<div style='display:flex;justify-content:space-between;align-items:center;padding:0.5rem 0;border-bottom:1px solid var(--border)'><div><span style='color:var(--cream)'>"+s.name+"</span><br><span style='font-size:0.75rem;color:var(--muted)'>"+s.method+" "+s.target_url+" &bull; "+s.concurrency+"x "+s.duration_seconds+"s</span></div><div style='display:flex;gap:0.25rem'><button class='btn btn-sm' onclick='runScenario("+s.id+")'>Run</button><button class='btn btn-sm btn-danger' onclick='deleteScenario("+s.id+")'>Del</button></div></div>";}).join("");}
async function loadRuns(){var data=await api("GET","/api/runs");var tbody=document.getElementById("runs-body");if(!data||!data.length){tbody.innerHTML="<tr><td colspan='7' class='empty'>No runs</td></tr>";return;}tbody.innerHTML=data.map(function(r){return "<tr><td style='color:var(--cream)'>"+r.scenario_name+"</td><td>"+r.total_requests+"</td><td>"+(r.rps||0).toFixed(1)+"</td><td>"+(r.avg_latency_ms||0).toFixed(0)+"ms</td><td>"+(r.p99_latency_ms||0).toFixed(0)+"ms</td><td style='color:"+(r.error_count>0?"#d9534f":"#5cb85c")+"'>"+r.error_count+"</td><td><span class='badge-"+(r.status==="done"?"g":"y")+"'>"+r.status+"</span></td></tr>";}).join("");}
async function createScenario(){var s={name:document.getElementById("f-name").value.trim(),target_url:document.getElementById("f-url").value.trim(),method:document.getElementById("f-method").value,concurrency:parseInt(document.getElementById("f-conc").value)||10,duration_seconds:parseInt(document.getElementById("f-dur").value)||30};if(!s.target_url){alert("URL required");return;}var res=await api("POST","/api/scenarios",s);if(res.error){alert(res.error);return;}document.getElementById("f-url").value="";document.getElementById("f-name").value="";load();}
async function runScenario(id){var res=await api("POST","/api/scenarios/"+id+"/run");if(res.error){alert(res.error);return;}alert(res.message);setTimeout(load,1000);}
async function deleteScenario(id){if(!confirm("Delete?"))return;await api("DELETE","/api/scenarios/"+id);load();}
load();setInterval(loadRuns,3000);
</script></body></html>`)
